### ISSUE TITLE
You don't seem to have any missions

### ISSUE THREAD

**Issue by Phantomsmedia** [The-Slime/missions#1]
pls make missions comrade

**Comment by The-Slime** [comment]
https://github.com/The-Slime/missions/tree/Gone-to-Plaid

**Comment by The-Slime** [comment]
Also not a real issue.

**Comment by Phantomsmedia** [comment]
I'm just messing around dude, forcing you to get used to issue tracking. Feel free to submit issues of the main phramework at that github too.
