### ISSUE TITLE
Chateau or Schloss: Anything even vaguely related to GL mags are not delivered

### ISSUE THREAD

**Issue by The-Slime** [The-Slime/missions#12]
SLs, PLT and FTLs do not get any rounds of any kind for their grenade launchers.

-Dummy class was made with only a uniform, vest, backpack (certainly enough to hold the magazines) and also does not receive the GL ammo
-Another variable with same contents as WEST_GLRIFLE_MAG_HE was created and called - ammo still not delivered
-When said variable is changed to contain rifle ammo instead of GL ammo, the rifle ammo is delivered to all requesting classes EXCEPT the dummy class

The long and short of it is WTF man. Send help.

Offending file: https://www.dropbox.com/s/8a0tofd3f99c4r4/bluefor_standard.hpp?dl=0

**Comment by batboyx2** [comment]
I know KillPact was having exactly this problem at one point.

**Comment by The-Slime** [comment]
Issue has been resolved by adding the mags as backpack items - will commit shortly
