### ISSUE TITLE
Bad Dream: assignGears, Red brief, desc.ext, loadLogo

### ISSUE THREAD

**Issue by The-Slime** [The-Slime/missions#6]

**Comment by Phantomsmedia** [comment]
What is this? Anything we can solve in https://github.com/Phantomsmedia/Wavelength

**Comment by The-Slime** [comment]
I get the feel you are misunderstanding this. This is just doing the load screen stuff, briefings, and loadouts for 1 mission using already existing files...

**Comment by Phantomsmedia** [comment]
Just asking, I see what you're doing now, sorry. : P 

Thought you meant something was broken somehow.

**Comment by The-Slime** [comment]
If there was something broken I would have used the bug label. The todo label is for when something is not broken but simply still needs doing.

**Comment by The-Slime** [comment]
Red brief done...

**Comment by The-Slime** [comment]
desc.ext done...

**Comment by The-Slime** [comment]
loadLogo done. Now for the loadouts...

_The only easy day was yesterday..._
